# My first Action
# Create DIR on remote server with SSH

name: Deployed

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.HOST }}

      - name: Create folders
        run : mkdir ${{ github.sha }}
        
      - name: Copy to Server
        run : rsync -a -e "ssh" . ubuntu@${{ secrets.HOST }}:/home/ubuntu
